AWSTemplateFormatVersion: '2010-09-09'
Description: EC2 creada desde GitHub Actions por Dairo

Parameters:
  InstanceDescription:
    Description: Descripcion del servidor web
    Type: String
    Default: Servidor Web Apache

  SecurityGroupDescription:
    Description: Security Group Description
    Type: String
    Default: Acceso HTTP al servidor

  LatestAmiId:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64'

Resources:

  MyInstanceClase:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref LatestAmiId
      InstanceType: t2.micro
      SecurityGroups:
        - !Ref ServerSecurityGroupClase
      Tags:
        - Key: Name
          Value: EC2-Clase-CF
        - Key: Proyecto
          Value: Class-CloudFormation
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          yum install -y httpd
          systemctl start httpd
          systemctl enable httpd
          echo "<html><head><meta charset='utf-8'></head><body>
          <h1>${InstanceDescription} 👏</h1>
          <h2>Despliegue exitoso desde pipeline: deploy.yaml 🚀</h2>
          </body></html>" > /var/www/html/index.html

  ServerSecurityGroupClase:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Ref SecurityGroupDescription
      Tags:
        - Key: Name
          Value: SG-HTTP-Clase-CF
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

Outputs:
  InstanceId:
    Value: !Ref MyInstanceClase